### ISSUE TITLE
One way communication using Eos V 2.4.  HELP!!

### ISSUE THREAD

**Issue by BoyOfWonder** [ElectronicTheatreControlsLabs/OSCLayouts#19]
I'm getting one way communication using Touch OSC and and Ion Console running the Eos software V2.4.  The TouchOSC app see the communication from the Ion, but none of the command sent from the TouchOSC app is been received by the console.

I've double and triple check all inputs to make sure that everything is correct and I can find an issue.  It seems like the app isn't even sending out ANY thing.  The red communication indicator in the app blinks when the app is seeing what's going on at the console and the command line on the app mirrors everything from the console.  However, if I try to input commands into the app nothing happy, including the green indicator light in the top right hand corner of the app not blinking at all.

Any ideas?

Thanks
p.s., I'm also running the latest version of the TouchOSC app on an iPad using iOS 10.

**Comment by Druuka** [comment]
I would suggest that the ETC forums are a better place to ask this question. There are many more people monitoring that than this.

If the green light isn't flashing when you press a button then there is probably something messed up with your touchosc setup.  First off I would suggest killing the app and restarting your device.  Then load one of the generic layouts and see if you get green flashes to determine if possibly the layout file is corrupt or misloaded.

**Comment by BoyOfWonder** [comment]
Yup, makes sense.  Was just about to do that as well.  Thanks so much for the feedback.
